//
//  FastList
//  Tests
//
//  Source generated by Haxe Objective-C target
//




@interface FastCell : HXObject

@property (nonatomic) id elt;
@property (nonatomic, strong) FastCell *next;
- (id) init:(id)elt next:(FastCell*)next;

@end


#import <Foundation/Foundation.h>


@interface FastList : HXObject

@property (nonatomic, strong) FastCell *head;
- (void) add:(id)item;
- (id) first;
- (id) pop;
- (BOOL) isEmpty;
- (BOOL) remove:(id)v;
- (id) iterator;
- (NSMutableString*) toString;
- (id) init;

@end

