//
//  TestC
//  Tests
//
//  Source generated by Haxe Objective-C target
//



#import "NSObjCRuntime.h"
#import <objc/runtime.h>

@interface TestC : HXObject

- (void) testMath;
- (id) init;

@end

