//
//  ObjectMap
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "../../Array.h"

@interface NSMutableDictionary ( ObjectMap )

- (id) get:(id)key;
- (void) set:(id)key value:(id)value;
- (BOOL) exists:(id)key;
- (id) keys;
- (id) init;

@end

