//
//  MySubClass
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/MySubClass.h"

@implementation MySubClass

static int XXX;
+ (int) XXX {
	if (XXX == nil) XXX = 3;
	return XXX;
}
+ (void) setXXX:(int)hx_val {
	XXX = hx_val;
}
- (int) get{
	return self.val * 2;
}

@end
