//
//  MyUsing2
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/MyUsing2.h"

@implementation Using2

+ (NSMutableString*) usingTest:(NSMutableString*)s{
	
	return [@"2" mutableCopy];
}

@end

@implementation Using3

+ (NSMutableString*) usingTest:(NSMutableString*)s{
	
	return [@"3" mutableCopy];
}

@end
