//
//  TestMeta
//  Test
//
//  Source generated by Haxe Objective-C target
//

typedef enum{
	A,
	B
} E;


#import "../String.h"
#import "../Array.h"
#import "../Reflect.h"
#import "../haxe/rtti/Meta.h"
#import "../unit/TestMeta.h"
#import "../Std.h"
#import "../unit/Test.h"

@interface TestMeta : Test 

+ (id) __meta__;
+ (void) set__meta__:(id)val;
+ (int) foo;
+ (void) setFoo:(int)val;
- (NSMutableString*) fields:(id)o;
- (void) testMeta;
- (void) testExprMeta;
- (id) init;

@end

