//
//  TestOps
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/TestOps.h"

@implementation TestOps

- (void) testOps{
	[self eq:[@"3" stringByAppendingString:[NSMutableString stringWithString:@""]] v2:[NSMutableString stringWithString:@"3"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"7",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:[@"3" stringByAppendingString:[NSMutableString stringWithString:@""]] v2:[NSMutableString stringWithString:@"3"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"8",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:1 +  ([@"2" stringByAppendingString:[NSMutableString stringWithString:@""]]) v2:[NSMutableString stringWithString:@"12"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"9",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:[@"1" stringByAppendingString:[NSMutableString stringWithString:@""]] v2:[NSMutableString stringWithString:@"1"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"11",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:[@"1" stringByAppendingString:[NSMutableString stringWithString:@""]] v2:[NSMutableString stringWithString:@"1"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"12",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"15",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"16",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"17",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"19",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"20",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:0 v2:0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"21",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:-4 v2:-4 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"23",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:-6 v2:-6 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"24",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:YES pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"26",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:YES pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"27",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:YES pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"28",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:YES pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"29",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 % 3 * 4 v2:8 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"31",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 % 3 * 4 v2:8 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"32",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 % 12 v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"33",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5. v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"35",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5. v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"36",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:20. v2:20 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"37",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:8 v2:8 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"39",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:8 v2:8 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"40",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:4 v2:4 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"41",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self f:NO pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"43",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self f:NO pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"44",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self f:NO pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"45",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self f:NO pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"46",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 *  (10 % 3) v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"48",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 *  (10 % 3) v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"49",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:50 % 3 v2:2 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"50",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:10 % 3 * 5 v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"52",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:10 % 3 * 5 v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"53",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:10 % 15 v2:10 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"54",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:100 % 100 v2:0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"55",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:-100 % 100 v2:0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"56",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:101.5 % 100 v2:1.5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"57",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:-101.5 % 100 v2:-1.5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"58",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	float x = 101.5;
	x %= 100;
	[self eq:x v2:1.5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"61",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:isnan(5.0 % 0.0) pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"62",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:isnan(x %= 0.0) pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"63",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	id x1 = [[NSMutableArray alloc] initWithObject:[NSNumber numberWithFloat:-101.5]];
	[x1 hx_objectAtIndex:0] %= 100;
	[self eq:[x1 hx_objectAtIndex:0] v2:-1.5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"71",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"72",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:30 v2:30 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"73",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"74",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:30 v2:30 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"75",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:2 v2:2 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"77",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:5 v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"78",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:1 v2:1 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"80",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:YES pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"81",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	BOOL k = NO;
	[self f:k = NO pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"84",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self f:k pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"85",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self f:( (k = YES) ? NO : YES) pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"86",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:k pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"87",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self t:YES pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"89",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	int x2 = 1;
	[self eq:-x2++ v2:-1 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"92",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:-x2-- v2:-2 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"93",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:[ ([[NSMutableString stringWithString:@"bla"] stringByAppendingString:[NSMutableString stringWithString:@"x"]]) indexOf:[NSMutableString stringWithString:@"x"] startIndex:nil] v2:3 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"95",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:19 v2:19 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"97",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
	[self eq:19 v2:19 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestOps.hx",@"fileName", @"98",@"lineNumber", @"unit.TestOps",@"className", @"testOps",@"methodName", nil]];
}
- (id) init{
	self = [super init];
	return self;
}

@end
