//
//  TestOrder
//  Test
//
//  Source generated by Haxe Objective-C target
//

typedef enum{
	C1
} E1;
typedef enum{
	C1
} E2;


#import "../unit/MyUsing2.h"
#import "../unit/TestOrder.h"
#import "../unit/Test.h"

@interface TestOrder : Test 

- (void) testUsing;

@end

