//
//  TestEReg
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/TestEReg.h"

@implementation TestEReg

- (void) test{
	
	NSMutableArray *r = [[NSMutableArray alloc] initWithObject:[[EReg alloc] init:[NSMutableString stringWithString:@"a+(b)?(c*)a+"] opt:[NSMutableString stringWithString:@""]]];
	[self f:[[r hx_objectAtIndex:0] match:[NSMutableString stringWithString:@""]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"9",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[[r hx_objectAtIndex:0] match:[NSMutableString stringWithString:@"xxyy"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"10",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[r hx_objectAtIndex:0] match:[NSMutableString stringWithString:@"xxaabcayyy"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"11",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matched:0] v2:[NSMutableString stringWithString:@"aabca"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"12",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matched:1] v2:[NSMutableString stringWithString:@"b"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"13",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matched:2] v2:[NSMutableString stringWithString:@"c"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"14",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matchedLeft] v2:[NSMutableString stringWithString:@"xx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"15",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matchedRight] v2:[NSMutableString stringWithString:@"yyy"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"16",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matchedPos] pos v2:2 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"17",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matchedPos] len v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"18",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[r hx_objectAtIndex:0] match:[NSMutableString stringWithString:@"aaa"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"20",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matched:0] v2:[NSMutableString stringWithString:@"aaa"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"21",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matchedLeft] v2:[NSMutableString stringWithString:@""] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"22",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matchedRight] v2:[NSMutableString stringWithString:@""] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"23",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matched:1] v2:nil pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"24",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[r hx_objectAtIndex:0] matched:2] v2:[NSMutableString stringWithString:@""] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"25",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self unspec:^- (void) {
		[[r hx_objectAtIndex:0] matched:3];
	} pos:nil];
	[self unspec:^- (void) {
		[[r hx_objectAtIndex:0] matched:-1];
	} pos:nil];
	
	EReg *r1 = [[EReg alloc] init:[NSMutableString stringWithString:@"^(b)?$"] opt:[NSMutableString stringWithString:@""]];
	[self t:[r1 match:[NSMutableString stringWithString:@""]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"30",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r1 matched:0] v2:[NSMutableString stringWithString:@""] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"31",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r1 matched:1] v2:nil pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"32",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[[EReg alloc] init:[NSMutableString stringWithString:@"/"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"/"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"34",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[[EReg alloc] init:[NSMutableString stringWithString:@"\n"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\n"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"36",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\\\n"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\n"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"37",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\\\n"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\\n"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"38",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[[EReg alloc] init:[NSMutableString stringWithString:@"\""] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\""]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"40",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\\\\""] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\""]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"41",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\\\\""] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\\\""]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"42",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\$"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"$"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"44",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\\\$"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"$"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"45",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\\\$"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\\$"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"46",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[[[EReg alloc] init:[NSMutableString stringWithString:@"\\\\\\$"] opt:[NSMutableString stringWithString:@""]] match:[NSMutableString stringWithString:@"\\$"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"47",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	EReg *r2 = [[EReg alloc] init:[NSMutableString stringWithString:@"cat"] opt:[NSMutableString stringWithString:@"g"]];
	[self t:[r2 match:[NSMutableString stringWithString:@"catneko"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"51",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[r2 match:[NSMutableString stringWithString:@"catneko"]] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"52",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@""]] replace:[NSMutableString stringWithString:@"aabbccaa"] by:[NSMutableString stringWithString:@"x"]] v2:[NSMutableString stringWithString:@"xbbccaa"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"54",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@"g"]] replace:[NSMutableString stringWithString:@"aabbccaa"] by:[NSMutableString stringWithString:@"x"]] v2:[NSMutableString stringWithString:@"xbbccx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"55",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	NSMutableString *test = [NSMutableString stringWithString:@"{ test } .blah  { something:someval } "];
	
	EReg *block = [[EReg alloc] init:[NSMutableString stringWithString:@"\\s*\\{\\s*|\\s*\\}\\s*"] opt:[NSMutableString stringWithString:@"gm"]];
	[self eq:[block split:test].length v2:5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"60",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[NSMutableString stringWithString:@"\""] stringByAppendingString:[[block split:test] join:[NSMutableString stringWithString:@"\",\""]]] stringByAppendingString:[NSMutableString stringWithString:@"\""]] v2:[NSMutableString stringWithString:@"\"\",\"test\",\".blah\",\"something:someval\",\"\""] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"61",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@"g"]] map:[NSMutableString stringWithString:@"aaabacx"] f:^- (NSMutableString*) :(EReg*)r3{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[[r3 matched:@"0"] substr:@"1" len:nil]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[aa]b[]cx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"64",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@""]] map:[NSMutableString stringWithString:@"aaabacx"] f:^- (NSMutableString*) :(EReg*)r3{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[[r3 matched:@"0"] substr:@"1" len:nil]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[aa]bacx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"65",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"a+(b*)"] opt:[NSMutableString stringWithString:@"g"]] map:[NSMutableString stringWithString:@"aaabacx"] f:^- (NSMutableString*) :(EReg*)r3{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[r3 matched:@"1"]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[b][]cx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"67",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@"g"]] map:[NSMutableString stringWithString:@"aaabacx"] f:^- (NSMutableString*) :(EReg*)r3{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[r3 matchedRight]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[bacx]b[cx]cx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"68",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@"g"]] map:[NSMutableString stringWithString:@"aaabacxa"] f:^- (NSMutableString*) :(EReg*)r3{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[r3 matchedLeft]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[]b[aaab]cx[aaabacx]"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"72",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	EReg *r3 = [[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@"g"]];
	[self eq:[r3 map:[NSMutableString stringWithString:@"aaabacx"] f:^- (NSMutableString*) :(EReg*)r4{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[r4 matchedLeft]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[]b[aaab]cx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"76",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r3 map:[NSMutableString stringWithString:@"aaabacx"] f:^- (NSMutableString*) :(EReg*)r4{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[r4 matchedLeft]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[]b[aaab]cx"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"77",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	EReg *r4 = [[EReg alloc] init:[NSMutableString stringWithString:@"a+"] opt:[NSMutableString stringWithString:@""]];
	[self t:[r4 matchSub:[NSMutableString stringWithString:@"abab"] pos:0 len:nil] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"81",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedRight] v2:[NSMutableString stringWithString:@"bab"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"82",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[r4 matchSub:[NSMutableString stringWithString:@"abab"] pos:1 len:nil] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"83",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedRight] v2:[NSMutableString stringWithString:@"b"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"84",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedLeft] v2:[NSMutableString stringWithString:@"ab"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"85",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[r4 matchSub:[NSMutableString stringWithString:@"abab"] pos:0 len:nil] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"87",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedRight] v2:[NSMutableString stringWithString:@"bab"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"88",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[r4 matchSub:[NSMutableString stringWithString:@"abab"] pos:1 len:nil] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"89",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedRight] v2:[NSMutableString stringWithString:@"b"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"90",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedLeft] v2:[NSMutableString stringWithString:@"ab"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"91",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[r4 matchSub:[NSMutableString stringWithString:@"bbaa"] pos:0 len:1] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"93",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[r4 matchSub:[NSMutableString stringWithString:@"bbaa"] pos:0 len:2] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"94",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self f:[r4 matchSub:[NSMutableString stringWithString:@"bbaa"] pos:1 len:1] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"95",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self t:[r4 matchSub:[NSMutableString stringWithString:@"bbaa"] pos:2 len:1] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"96",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedLeft] v2:[NSMutableString stringWithString:@"bb"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"97",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r4 matchedRight] v2:[NSMutableString stringWithString:@"a"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"98",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[[[EReg alloc] init:[NSMutableString stringWithString:@"x?"] opt:[NSMutableString stringWithString:@"g"]] map:[NSMutableString stringWithString:@"aaabacx"] f:^- (NSMutableString*) :(EReg*)r5{
		return [[[NSMutableString stringWithString:@"["] stringByAppendingString:[r5 matched:@"0"]] stringByAppendingString:[NSMutableString stringWithString:@"]"]];
	}] v2:[NSMutableString stringWithString:@"[]a[]a[]a[]b[]a[]c[x]"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"100",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	SEL f = ^- (NSMutableString*) :(id)x{
		return [[[[[[[[[NSMutableString stringWithString:@"(["] stringByAppendingString:[x matchedLeft]] stringByAppendingString:[NSMutableString stringWithString:@"]"]] stringByAppendingString:[NSMutableString stringWithString:@"["]] stringByAppendingString:[x matched:@"0"]] stringByAppendingString:[NSMutableString stringWithString:@"]"]] stringByAppendingString:[NSMutableString stringWithString:@"["]] stringByAppendingString:[x matchedRight]] stringByAppendingString:[NSMutableString stringWithString:@"])b"]];
	}
	
	EReg *r5 = [[EReg alloc] init:[NSMutableString stringWithString:@"$"] opt:[NSMutableString stringWithString:@"mg"]];
	[self eq:[r5 map:[NSMutableString stringWithString:@"\n"] f:f] v2:[NSMutableString stringWithString:@"([][][\n])b\n"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"104",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r5 map:[NSMutableString stringWithString:@"a"] f:f] v2:[NSMutableString stringWithString:@"a([a][][])b"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"105",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r5 map:[NSMutableString stringWithString:@"aa\na"] f:f] v2:[NSMutableString stringWithString:@"aa([aa][][\na])b\na([aa\na][][])b"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"106",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	EReg *r6 = [[EReg alloc] init:[NSMutableString stringWithString:@"^"] opt:[NSMutableString stringWithString:@"mg"]];
	[self eq:[r6 map:[NSMutableString stringWithString:@"\n"] f:f] v2:[NSMutableString stringWithString:@"([][][\n])b\n"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"110",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r6 map:[NSMutableString stringWithString:@"a"] f:f] v2:[NSMutableString stringWithString:@"([][][a])ba"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"111",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r6 map:[NSMutableString stringWithString:@"aa\na"] f:f] v2:[NSMutableString stringWithString:@"([][][aa\na])baa\n([aa\n][][a])ba"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"112",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	EReg *r7 = [[EReg alloc] init:[NSMutableString stringWithString:@"$"] opt:[NSMutableString stringWithString:@"m"]];
	[self eq:[r7 map:[NSMutableString stringWithString:@"\n"] f:f] v2:[NSMutableString stringWithString:@"([][][\n])b\n"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"115",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r7 map:[NSMutableString stringWithString:@"a"] f:f] v2:[NSMutableString stringWithString:@"a([a][][])b"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"116",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r7 map:[NSMutableString stringWithString:@"aa\na"] f:f] v2:[NSMutableString stringWithString:@"aa([aa][][\na])b\na"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"117",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	EReg *r8 = [[EReg alloc] init:[NSMutableString stringWithString:@"^"] opt:[NSMutableString stringWithString:@"m"]];
	[self eq:[r8 map:[NSMutableString stringWithString:@"\n"] f:f] v2:[NSMutableString stringWithString:@"([][][\n])b\n"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"121",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r8 map:[NSMutableString stringWithString:@"a"] f:f] v2:[NSMutableString stringWithString:@"([][][a])ba"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"122",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	[self eq:[r8 map:[NSMutableString stringWithString:@"aa\na"] f:f] v2:[NSMutableString stringWithString:@"([][][aa\na])baa\na"] pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"123",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
	
	NSMutableArray *r9 = [[NSMutableArray alloc] initWithObject:[[EReg alloc] init:[NSMutableString stringWithString:@"a"] opt:[NSMutableString stringWithString:@""]]];
	[self exc:^- (void) {
		[[r9 hx_objectAtIndex:0] matched:0];
	} pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestEReg.hx",@"fileName", @"126",@"lineNumber", @"unit.TestEReg",@"className", @"test",@"methodName", nil]];
}
- (id) init{
	self = [super init];
	return self;
}

@end
