//
//  TestIO
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/TestIO.h"

@implementation TestIO

- (void) test{
	[self check:NO];
	[self check:YES];
}
- (void) excv:(SEL)f e:(id)e pos:(id)pos{
	// Optional arguments
	if (!pos) pos = nil;
	
	@try {
		[f];
		[self eq:nil v2:e pos:pos];
	}
	@catch (NSException *e2) {
		[self eq:e2 v2:e pos:pos];
	}
}
- (void) check:(BOOL)endian{
	[self infos:[[NSMutableString stringWithString:@"endian = "] stringByAppendingString:[Std string:endian]]];
	
	NSMutableArray *b = [[NSMutableArray alloc] initWithObject:[Bytes ofString:[NSMutableString stringWithString:@"ABCééé\r\n\t"]]];
	[self eq:[b hx_objectAtIndex:0].length v2:12 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"24",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[b hx_replaceObjectAtIndex:0.b hx_replaceObjectAtIndex:1 withObject:[NSNumber numberWithInt:0]];
	
	NSMutableArray *o = [[NSMutableArray alloc] initWithObject:[[BytesOutput alloc] init]];
	[[o hx_objectAtIndex:0] set_bigEndian:endian];
	[self eq:[o hx_objectAtIndex:0].bigEndian v2:endian pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"30",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[[o hx_objectAtIndex:0] prepare:4];
	[[o hx_objectAtIndex:0] writeByte:0];
	[[o hx_objectAtIndex:0] writeByte:1];
	[[o hx_objectAtIndex:0] writeByte:2];
	[[o hx_objectAtIndex:0] writeByte:3];
	[[o hx_objectAtIndex:0] write:[b hx_objectAtIndex:0]];
	[[o hx_objectAtIndex:0] writeByte:55];
	[[o hx_objectAtIndex:0] writeBytes:[b hx_objectAtIndex:0] pos:3 len:5];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeBytes:[b hx_objectAtIndex:0] pos:-1 len:5];
	} e: OutsideBounds pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"41",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeBytes:[b hx_objectAtIndex:0] pos:3 len:-1];
	} e: OutsideBounds pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"42",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeBytes:[b hx_objectAtIndex:0] pos:3 len:20];
	} e: OutsideBounds pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"43",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[[o hx_objectAtIndex:0] writeByte:98];
	[[o hx_objectAtIndex:0] writeDouble:1.23];
	[[o hx_objectAtIndex:0] writeDouble:-1.23];
	[[o hx_objectAtIndex:0] writeDouble:0.0];
	[[o hx_objectAtIndex:0] writeDouble:-0.0];
	[[o hx_objectAtIndex:0] writeFloat:1.2e10];
	[[o hx_objectAtIndex:0] writeFloat:-1.2e10];
	[[o hx_objectAtIndex:0] writeFloat:0.0];
	[[o hx_objectAtIndex:0] writeFloat:-0.0];
	[[o hx_objectAtIndex:0] writeByte:99];
	
	NSMutableString *str = [NSMutableString stringWithString:@"Héllo World !"];
	[[o hx_objectAtIndex:0] writeString:str];
	[[o hx_objectAtIndex:0] writeInt16:-12345];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeInt16:32768];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"60",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeInt16:-32769];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"61",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[[o hx_objectAtIndex:0] writeInt24:-1234567];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeInt16:16777216];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"63",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeInt16:-16777217];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"64",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[[o hx_objectAtIndex:0] writeInt32:-123456789];
	[[o hx_objectAtIndex:0] writeInt8:-5];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeInt8:128];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"68",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeInt8:-129];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"69",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[[o hx_objectAtIndex:0] writeUInt16:65365];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeUInt16:65536];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"71",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeUInt16:-1];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"72",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[[o hx_objectAtIndex:0] writeUInt24:16711918];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeUInt24:16777216];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"74",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self excv:^- (void) {
		[[o hx_objectAtIndex:0] writeUInt24:-1];
	} e: Overflow pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"75",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[[o hx_objectAtIndex:0] writeInt32:1068153804];
	[[o hx_objectAtIndex:0] writeInt32:-1593839907];
	[[o hx_objectAtIndex:0] writeInt32:-1056968995];
	[self unspec:^- (void) {
		[[o hx_objectAtIndex:0] writeByte:-1];
	} pos:nil];
	[self unspec:^- (void) {
		[[o hx_objectAtIndex:0] writeByte:257];
	} pos:nil];
	
	BytesInput *i = [[BytesInput alloc] init:[[o hx_objectAtIndex:0] getBytes] pos:nil len:nil];
	[i set_bigEndian:endian];
	[self eq:[i readInt32] v2:( (endian) ? 66051 : 50462976) pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"86",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[[i read:[b hx_objectAtIndex:0] length] compare:[b hx_objectAtIndex:0]] v2:0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"87",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readByte] v2:55 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"88",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[[i read:5] compare:[[b hx_objectAtIndex:0] sub:3 len:5]] v2:0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"89",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readByte] v2:98 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"91",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readDouble] v2:1.23 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"92",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readDouble] v2:-1.23 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"93",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readDouble] v2:0.0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"94",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readDouble] v2:-0.0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"95",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readFloat] v2:1.2e10 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"96",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readFloat] v2:-1.2e10 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"97",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readFloat] v2:0.0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"98",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readFloat] v2:-0.0 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"99",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readByte] v2:99 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"100",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readString:[Bytes ofString:str].length] v2:str pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"102",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readInt16] v2:-12345 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"104",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readInt24] v2:-1234567 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"105",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readInt32] v2:-123456789 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"106",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readInt8] v2:-5 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"107",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readUInt16] v2:65365 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"108",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readUInt24] v2:16711918 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"109",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readInt32] v2:1068153804 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"110",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readInt32] v2:-1593839907 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"112",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
	[self eq:[i readInt32] v2:-1056968995 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"113",@"lineNumber", @"unit.TestIO",@"className", @"check",@"methodName", nil]];
}
- (void) testBytesBounds{
	
	Bytes *b = [Bytes ofString:[NSMutableString stringWithString:@"ABCDEFGHIJ"]];
	
	NSMutableArray *tmp = [[NSMutableArray alloc] initWithObject:[Bytes alloc:[NSNumber numberWithInt:7]]];
	
	NSMutableArray *i = [[NSMutableArray alloc] initWithObject:[[BytesInput alloc] init:b pos:[NSNull null] len:[NSNull null]]];
	[self excv:^- (void) {
		[[i hx_objectAtIndex:0] readBytes:[tmp hx_objectAtIndex:0] pos:1 len:7];
	} e: OutsideBounds pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"121",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self excv:^- (void) {
		[[i hx_objectAtIndex:0] readBytes:[tmp hx_objectAtIndex:0] pos:-1 len:7];
	} e: OutsideBounds pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"122",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self excv:^- (void) {
		[[i hx_objectAtIndex:0] readBytes:[tmp hx_objectAtIndex:0] pos:8 len:1];
	} e: OutsideBounds pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"123",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self eq:[[i hx_objectAtIndex:0] readBytes:[tmp hx_objectAtIndex:0] pos:0 len:7] v2:7 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"124",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self eq:[[tmp hx_objectAtIndex:0].b hx_objectAtIndex:0] v2:65 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"125",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self eq:[[tmp hx_objectAtIndex:0].b hx_objectAtIndex:6] v2:71 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"126",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self eq:[[i hx_objectAtIndex:0] readBytes:[tmp hx_objectAtIndex:0] pos:0 len:7] v2:3 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"127",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self eq:[[tmp hx_objectAtIndex:0].b hx_objectAtIndex:0] v2:72 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"128",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self eq:[[tmp hx_objectAtIndex:0].b hx_objectAtIndex:2] v2:74 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"129",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self eq:[[tmp hx_objectAtIndex:0].b hx_objectAtIndex:3] v2:68 pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"130",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
	[self exc:^- (void) {
		[[i hx_objectAtIndex:0] readBytes:[tmp hx_objectAtIndex:0] pos:0 len:7];
	} pos:[NSDictionary dictionaryWithObjectsAndKeys:@"TestIO.hx",@"fileName", @"131",@"lineNumber", @"unit.TestIO",@"className", @"testBytesBounds",@"methodName", nil]];
}
- (id) init{
	self = [super init];
	return self;
}

@end
