//
//  TestSpecification
//  Test
//
//  Source generated by Haxe Objective-C target
//



#import "../String.h"
#import "../unit/TestSpecification.h"

@interface C : NSObject

+ (void) staticFunc;
+ (NSMutableString*) staticVar;
+ (void) setStaticVar:(NSMutableString*)val;
+ (NSMutableString*) staticProp;
+ (void) setStaticProp:(NSMutableString*)val;
- (void) func;
@property (nonatomic, strong) NSMutableString *v;
@property (nonatomic, strong) NSMutableString *prop;
- (id) init;

@end



#import "../String.h"

@interface C2 : NSObject

- (NSMutableString*) func;
@property (nonatomic, strong) NSMutableString *v;
@property (nonatomic, strong) NSMutableString *prop;
@property (nonatomic, strong, getter=get_propAcc, setter=set_propAcc) NSMutableString *propAcc;
- (NSMutableString*) get_propAcc;
- (NSMutableString*) set_propAcc:(id)v;
- (id) init;

@end



#import "../unit/TestSpecification.h"

@interface CChild : C 


@end



#import "../unit/TestSpecification.h"

@interface CDyn : C 


@end




@interface EmptyClass : NSObject

- (id) init;

@end



#import "../String.h"

@interface ClassWithToString : NSObject

- (NSMutableString*) toString;
- (id) init;

@end



#import "../unit/TestSpecification.h"

@interface ClassWithToStringChild : ClassWithToString 


@end



#import "../String.h"
#import "../unit/TestSpecification.h"

@interface ClassWithToStringChild2 : ClassWithToString 

- (NSMutableString*) toString;

@end



#import "../String.h"

@interface ClassWithCtorDefaultValues : NSObject

@property (nonatomic) int a;
@property (nonatomic, strong) NSMutableString *b;
- (id) init:(int)a b:(NSMutableString*)b;

@end



#import "../unit/TestSpecification.h"

@interface ClassWithCtorDefaultValuesChild : ClassWithCtorDefaultValues 


@end

typedef enum{
	NoArguments,
	OneArgument
} SomeEnum;


#import "../unit/TestSpecification.h"

@interface IntWrap : NSObject

+ (int) compare:(IntWrap*)a b:(IntWrap*)b;
@property (nonatomic) int i;
- (id) init:(int)i;

@end

typedef enum{
	NoArgs,
	OneArg,
	RecArg,
	MultipleArgs
} E;
typedef enum{
	EA,
	EB,
	EC
} EnumFlagTest;


#import "../unit/Test.h"

@interface TestSpecification : Test 


@end

