//
//  TestOrder
//  Test
//
//  Source generated by Haxe Objective-C target
//

#import "../unit/TestOrder.h"

@implementation TestOrder

- (void) testUsing{
	
	[self eq:[Using3 usingTest:[@"foo" mutableCopy]] v2:[@"3" mutableCopy] pos:@{@"fileName":@"TestOrder.hx", @"lineNumber":@"17", @"className":@"unit.TestOrder", @"methodName":@"testUsing"}];
	
	E2 *c = C1;
	{
		
		count++;
		[self eq:[@"TEnum(unit.E2,[])" mutableCopy] v2:[@"TEnum(unit.E2,[])" mutableCopy] pos:@{@"fileName":@"TestOrder.hx", @"lineNumber":@"21", @"className":@"unit.TestOrder", @"methodName":@"testUsing"}];
	}
	[self eq:c v2:C1 pos:@{@"fileName":@"TestOrder.hx", @"lineNumber":@"22", @"className":@"unit.TestOrder", @"methodName":@"testUsing"}];
}

@end
