//
//  BalancedTree
//  Tests
//
//  Source generated by Haxe Objective-C target
//



#import "../../haxe/ds/BalancedTree.h"
#import "../../Array.h"
#import "../../Reflect.h"
#import "../../String.h"

@interface BalancedTree : NSObject

@property (nonatomic, strong) TreeNode *root;
- (void) set:(id)k v:(id)v;
- (id) get:(id)k;
- (BOOL) remove:(id)k;
- (BOOL) exists:(id)k;
- (id) iterator;
- (id) keys;
- (TreeNode*) setLoop:(id)k v:(id)v node:(TreeNode*)node;
- (TreeNode*) removeLoop:(id)k node:(TreeNode*)node;
- (void) iteratorLoop:(TreeNode*)node acc:(NSMutableArray*)acc;
- (void) keysLoop:(TreeNode*)node acc:(NSMutableArray*)acc;
- (TreeNode*) merge:(TreeNode*)t1 t2:(TreeNode*)t2;
- (TreeNode*) minBinding:(TreeNode*)t;
- (TreeNode*) removeMinBinding:(TreeNode*)t;
- (TreeNode*) balance:(TreeNode*)l k:(id)k v:(id)v r:(TreeNode*)r;
- (int) compare:(id)k1 k2:(id)k2;
- (NSMutableString*) toString;
- (id) init;

@end



#import "../../haxe/ds/BalancedTree.h"
#import "../../String.h"
#import "../../Std.h"

@interface TreeNode : NSObject

@property (nonatomic, strong) TreeNode *left;
@property (nonatomic, strong) TreeNode *right;
@property (nonatomic) id key;
@property (nonatomic) id value;
@property (nonatomic) int _height;
- (NSMutableString*) toString;
- (id) init:(TreeNode*)l k:(id)k v:(id)v r:(TreeNode*)r h:(int)h;

@end

