//
//  StringMap
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "../../haxe/ds/StringMap.h"

@implementation NSMutableDictionary ( StringMap )

- (void) set:(NSMutableString*)key value:(id)value{
	
	[self setObject:value forKey:key];
}
- (id) get:(NSMutableString*)key{
	
	return [self objectForKey:key];
}
- (BOOL) exists:(NSMutableString*)key{
	
	return [self objectForKey:key] != nil;
}
- (BOOL) remove:(NSMutableString*)key{
	
	if ([self exists:key]) {
		
		[self removeObjectForKey:key];
		return YES;
	}
	return NO;
}
- (id) keys{
	
	
	NSMutableArray *a = [self allKeys];
	return [a iterator];
}
- (id) iterator{
	
	
	NSMutableArray *a = [self allValues];
	id it = [a iterator];
	
	StringMap *me = self;
	return [@{
		@"hasNext":[^(){
		
		return [it hasNext];
	} copy],
		@"next":[^(){
		
		return [me __Internal __Field:[it next] :YES];
	} copy],
	} mutableCopy];
}
- (NSMutableString*) toString{
	
	return [self description];
}
- (id) init{
	
	self = [super init];
	return self;
}

@end
