//
//  WeakMap
//  Tests
//
//  Source generated by Haxe Objective-C target
//

#import "../../haxe/ds/WeakMap.h"

@implementation WeakMap

- (void) set:(id)_tmp_key _tmp_value:(id)_tmp_value{
	id key = (id)_tmp_key; id value = (id)_tmp_value;
}
- (id) get:(id)_tmp_key{
	id key = (id)_tmp_key;
	return nil;
}
- (BOOL) exists:(id)_tmp_key{
	id key = (id)_tmp_key;
	return NO;
}
- (BOOL) remove:(id)_tmp_key{
	id key = (id)_tmp_key;
	return NO;
}
- (id) keys{
	return nil;
}
- (id) iterator{
	return nil;
}
- (NSMutableString*) toString{
	return nil;
}
- (id) init{
	self = [super init];
	@throw [@"Not implemented for this platform" mutableCopy];;
	return self;
}

@end
