//
//  WeakMap
//  Tests
//
//  Source generated by Haxe Objective-C target
//



#import "../../String.h"

@interface WeakMap : NSObject<IMap>

- (void) set:(id)key value:(id)value;
- (id) get:(id)key;
- (BOOL) exists:(id)key;
- (BOOL) remove:(id)key;
- (id) keys;
- (id) iterator;
- (NSMutableString*) toString;
- (id) init;

@end

